name: scala
version: '@VERSION@'
summary: The Scala Programming Language
description: |
  Scala combines object-oriented and functional programming in one concise,
  high-level language. Scala's static types help avoid bugs in complex
  applications, and its JVM and JavaScript runtimes let you build high-performance
  systems with easy access to huge ecosystems of libraries.

confinement: strict
base: core20

parts:
  scala:
    plugin: dump
    source: '@URL@'
    source-type: zip

apps:
  scala:
    command: bin/scala
  scalac:
    command: bin/scalac
  scaladoc:
    command: bin/scaladoc

