name: Scala CLA
on:
  # This is a temporary trigger to cover already opened PRs
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'language-reference-stable'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CLA
        uses: scala/cla-checker@v1
        with:
          author: ${{ github.event.pull_request.user.login }}
