name: Check Scala CLA
on:
  # This is a temporary trigger to cover already opened PRs
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - 'language-reference-stable'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./project/scripts/check-cla.sh
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
