###################################################################################################
###                          THIS IS A REUSABLE WORKFLOW TO TEST MiMa                           ###
### HOW TO USE:                                                                                 ###
###   - ???                                                                                     ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - ???                                                                                     ###
###################################################################################################

name: MiMa check
run-name: MiMa check

on:
  workflow_call:
    secrets:
      develocity-key:
        required: true

env:
  DOTTY_CI_RUN: true
  DEVELOCITY_ACCESS_KEY: ${{ secrets.develocity-key }}

jobs:
  MiMa:
    runs-on: [self-hosted, Linux]
    container:
      image: lampepfl/dotty:2024-10-18
      options: --cpu-shares 4096
      volumes:
        - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
        - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
        - ${{ github.workspace }}/../../cache/general:/root/.cache
    steps:
      - name: Set JDK 17 as default
        run: echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH

      - name: Reset existing repo
        run: |
          git config --global --add safe.directory /__w/scala3/scala3
          git -c "http.https://github.com/.extraheader=" fetch --recurse-submodules=no "https://github.com/scala/scala3" && git reset --hard FETCH_HEAD || true

      - name: Checkout cleanup script
        uses: actions/checkout@v4

      - name: Cleanup
        run: .github/workflows/cleanup.sh

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Add SBT proxy repositories
        run: cp -vf .github/workflows/repositories /root/.sbt/ ; true

      - name: MiMa
        run: |
          ./project/scripts/sbt ";scala3-interfaces/mimaReportBinaryIssues ;scala3-library-bootstrapped/mimaReportBinaryIssues ;scala3-library-bootstrappedJS/mimaReportBinaryIssues; tasty-core-bootstrapped/mimaReportBinaryIssues; scala2-library-bootstrapped/mimaReportBinaryIssues"

      - name: TASTy MiMa
        run: |
          # This script cleans the compiler and recompiles it from scratch (keep as last run)
          ./project/scripts/scala2-library-tasty-mima.sh